# Generated by Django 3.0.4 on 2020-04-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataquality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Загрузите файл')),
                ('source', models.URLField(verbose_name='Укажите его источник')),
                ('availability', models.FloatField(blank=True, default=None, null=True, verbose_name='Доступность')),
                ('authority', models.FloatField(blank=True, default=None, null=True, verbose_name='Авторитетность')),
                ('popularuty', models.FloatField(blank=True, default=None, null=True, verbose_name='Репутация')),
                ('machinereadability', models.FloatField(blank=True, default=None, null=True, verbose_name='Интерпретируемость')),
                ('reliability', models.FloatField(blank=True, default=None, null=True, verbose_name='Достоверность')),
                ('relevance', models.FloatField(blank=True, default=None, null=True, verbose_name='Актуальность')),
                ('fullness', models.FloatField(blank=True, default=None, null=True, verbose_name='Полнота')),
                ('classificators', models.CharField(blank=True, choices=[(1, 'INN'), (2, 'OGRN')], default=None, max_length=100, null=True)),
            ],
        ),
    ]
