# Generated by Django 3.0.4 on 2020-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200405_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='dataquality',
            name='full_classificators',
            field=models.ManyToManyField(to='mainapp.Choices', verbose_name='Укажите данные, которые вам нужны'),
        ),
    ]
