# Generated by Django 3.0.4 on 2020-04-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200412_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularuty_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularuty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Оцените качество источника данных по шкале от 1 до 10, исходя из произведенной оценки')),
                ('pk_Dataquality', models.IntegerField()),
            ],
        ),
    ]
