# Generated by Django 3.0.4 on 2020-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200413_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularuty_m',
            name='source_Dataquality',
            field=models.URLField(default=1, verbose_name='Укажите его источник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popularuty_m',
            name='pk_Dataquality',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='popularuty_m',
            name='popularuty_1',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Оцените качество источника данных по шкале от 1 до 10, исходя из произведенной оценки'),
        ),
    ]
