# Generated by Django 3.0.4 on 2020-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200414_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataquality',
            name='authority_full',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Авторитетность абсолютная'),
        ),
    ]
